SRCS=main.hcl
GEN_OPTS=-no_stdlib -dump_typed -dump_ir
DOT_OPTS=-target_dir ./dot -dot_slotted_boxes -dot_show_indexes
SYSTEMC_OPTS=-target_dir ./systemc -sc_stop_time 100 -sc_trace

include ../../../../lib/etc/Makefile.app
