PROJ=stabilization
SRCS=top.hcl
MAIN=top
GEN_OPTS=#-dump_static
DOT_OPTS=-dot_unlabeled_edges #-dot_simple_boxes 
#PREESM_OPTS=-preesm_top_name top -target_dir ./preesm
PREESM_OPTS=-target_dir ./preesm

include ../../../../lib/etc/Makefile.app
