PROJ=mini
SRCS=main.hcl
MAIN=main
DOT_OPTS=
PREESM_REP=/Users/jserot/Desktop/SF2/preesm-dev
PREESM_OPTS=-target_dir preesm
SYSTEMC_OPTS=-target_dir systemc -sc_stop_time 100

include ../../../../lib/etc/Makefile.app
