SRCS=main.hcl
GEN_OPTS=-prelude ../../../../lib/hocl/prelude.hcl
DOT_OPTS=-dot_slotted_boxes #-dump_static
#PREESM_OPTS=-preesm_top_name top_sobel -target_dir ./preesm
PREESM_OPTS=-target_dir ./preesm
SYSTEMC_OPTS=-target_dir ./systemc -sc_default_fifo_capacity 102000

include ../../../../lib/etc/Makefile.app
