SRCS=main.hcl
GEN_OPTS=
DOT_OPTS=-target_dir ./dot -dot_slotted_boxes
SYSTEMC_OPTS=-target_dir ./systemc -sc_default_fifo_capacity 102000 # Warning ! fifo cap must be big enough to hold one YUV frame
PREESM_OPTS=-target_dir ./preesm
PREESM_REP=/Users/jserot/Desktop/SF2/preesm-dev/sobel1
PREESM_PROJ=sobel1

include ../../../../lib/etc/Makefile.app
