// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 1.0a)
// from file(s) main.hcl, on 2020-03-07 at 11:42:00, by jserot
// -------------------------------------------------------------------------------

#ifndef _foo_act_h
#define _foo_act_h

#include <systemc.h>
#include "hocl.h"

SC_MODULE(Foo) {
  sc_in<bool> clk;
  sc_fifo_in<int > i;
  sc_fifo_out<int > o;

  void main(void);

  SC_HAS_PROCESS(Foo);

  Foo(sc_module_name name_, bool trace_=true  ) :
    modname(name_), sc_module(name_), trace(trace_) 
  {
    SC_THREAD(main);
  }

  ~Foo() { }

  private:
    // Local variables
    int _i[1];
    int _o[1];
    // Service
    bool trace;
    sc_module_name modname;
};
#endif
