#include <stdlib.h>
#include <string.h>

#include "delay.h"

void delay(int width, int height, int ival, IN unsigned char *input, OUT unsigned char *result)
{
  // Simply input to output (initial tokens will be generated by the enclosing actor)
  memcpy(result, input, width*height);
}
