SRCS=main.hcl
GEN_OPTS=-dump_typed
DOT_OPTS=-target_dir ./dot -dot_slotted_boxes
SYSTEMC_OPTS=-target_dir ./systemc -sc_stop_time 100
PREESM_OPTS=-target_dir ./preesm
PREESM_REP=/Users/jserot/Desktop/SF2/preesm-dev/simple
PREESM_PROJ=simple

include ../../../../lib/etc/Makefile.app
