SRCS=main.hcl
GEN_OPTS=
DOT_OPTS=-target_dir ./dot
SYSTEMC_OPTS=-target_dir ./systemc -sc_stop_time 100
PREESM_OPTS=-target_dir ./preesm
PREESM_REP=/Users/jserot/Desktop/SF2/preesm-dev/hier1
PREESM_PROJ=hier1

include ../../../../lib/etc/Makefile.app
