SRCS=main.hcl
MAIN=main
GEN_OPTS=#-dump_typed #-insert_fifos
DOT_OPTS=-target_dir ./dot
# SYSTEMC_OPTS=-target_dir systemc
# PREESM_OPTS=-target_dir preesm
# XDF_OPTS=-target_dir xdf

include ../../../../lib/etc/Makefile.app
