SRCS=main.hcl
GEN_OPTS=-dump_typed
DOT_OPTS=-target_dir ./dot
SYSTEMC_OPTS=-target_dir ./systemc
PREESM_OPTS=-target_dir ./preesm
PREESM_REP=/Users/jserot/Desktop/SF2/preesm-dev/multifilt
PREESM_PROJ=multifilt

include ../../../../lib/etc/Makefile.app
