// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 1.0a)
// from file(s) main.hcl, on 2020-03-07 at 11:42:00, by jserot
// -------------------------------------------------------------------------------

#include "foo_act.h"
#include "./include/foo.h"

void Foo::main(void) {
    while ( 1 ) { 
      for ( int __k=0; __k<1; __k++ ) _i[__k] = i.read();
      cout << modname << ": read: ";
      for ( int __k=0; __k<1; __k++ ) cout << _i[__k] << " ";
      cout << " at " << sc_time_stamp() << endl;
      foo(_i, _o);
      for ( int __k=0; __k<1; __k++ ) o.write(_o[__k]);
      cout << modname << ": wrote: ";
      for ( int __k=0; __k<1; __k++ ) cout << _o[__k] << " ";
      cout << " at " << sc_time_stamp() << endl;
    }
}
