// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 1.0a)
// from file(s) main.hcl, on 2020-03-07 at 11:42:00, by jserot
// -------------------------------------------------------------------------------

#include <systemc.h>
#include <iostream>
#include "stream_in.h"
#include "stream_out.h"
#include "param_in.h"
#include "delay.h"
#include "bcast.h"
#include "top_gph.h"

int sc_main(int argc, char* argv[]) {
  sc_clock clk("clk", 10, SC_NS, 0.5);

  sc_fifo<int> w1("w1",16);
  stream_in<int> top_i("top_i", "top_i.dat", true);
  top_i.clk(clk);
  top_i.out(w1);

  sc_fifo<int> w2("w2",16);
  stream_out<int> top_o("top_o", "top_o.dat", true);
  top_o.clk(clk);
  top_o.inp(w2);

  Top top("top");
  top.clk(clk);
  top.i(w1);
  top.o(w2);

  sc_start(100, SC_NS);
  cout << "Simulation stopped at t=" << sc_time_stamp() << "\n";
  return EXIT_SUCCESS;
}
