// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 1.0a)
// from file(s) main.hcl, on 2020-03-07 at 11:42:00, by jserot
// -------------------------------------------------------------------------------

#include <systemc.h>
#include <iostream>
#include "stream_in.h"
#include "stream_out.h"
#include "param_in.h"
#include "delay.h"
#include "bcast.h"
#include "foo_act.h"

SC_MODULE(Top) {
  sc_in<bool> clk;
  sc_fifo_in<int > i;
  sc_fifo_out<int > o;


  Foo foo3;

  SC_CTOR(Top) : foo3("foo3",true) {
    foo3.clk(clk);
    foo3.i(i);
    foo3.o(o);
  }
};
