// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 1.0a)
// from file(s) main.hcl, on 2020-02-26 at 15:08:46, by jserot
// -------------------------------------------------------------------------------

#include "inp_act.h"
#include "./include/input.h"

void Inp::main(void) {
    inputInit();
    while ( 1 ) { 
      wait(clk.posedge_event());
      input(_o);
      for ( int __k=0; __k<1; __k++ ) o.write(_o[__k]);
    }
}
