// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 1.0a)
// from file(s) main.hcl, on 2020-02-26 at 15:08:46, by jserot
// -------------------------------------------------------------------------------

#ifndef _inp_act_h
#define _inp_act_h

#include <systemc.h>
#include "hocl.h"

SC_MODULE(Inp) {
  sc_in<bool> clk;
  sc_fifo_out<int > o;

  void main(void);

  SC_HAS_PROCESS(Inp);

  Inp(sc_module_name name_, bool trace_=false  ) :
    modname(name_), sc_module(name_), trace(trace_) 
  {
    SC_THREAD(main);
  }

  ~Inp() { }

  private:
    // Local variables
    int _o[1];
    // Service
    bool trace;
    sc_module_name modname;
};
#endif
