// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 1.0a)
// from file(s) main.hcl, on 2020-02-26 at 15:08:46, by jserot
// -------------------------------------------------------------------------------

#include "mult_act.h"
#include "./include/mult.h"

void Mult::main(void) {
    wait(clk.posedge_event()); // Wait for all _signals_ to be initialized
    while ( 1 ) { 
      _k = k.read();
      for ( int __k=0; __k<1; __k++ ) _i[__k] = i.read();
      mult(_k, _i, _o);
      for ( int __k=0; __k<1; __k++ ) o.write(_o[__k]);
    }
}
