// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 1.0a)
// from file(s) main.hcl, on 2020-02-26 at 15:08:46, by jserot
// -------------------------------------------------------------------------------

#include <systemc.h>
#include <iostream>
#include "bcast.h"
#include "inParam.h"
#include "depParam.h"
#include "outp_act.h"
#include "mult_act.h"
#include "inp_act.h"

SC_MODULE(Top) {
  sc_in<bool> clk;
  sc_in<int > k;

  sc_fifo<int > w4; //("w4",16)
  sc_signal<int > w2;
  sc_fifo<int > w3; //("w3",16)
  sc_signal<int > w1;

  Outp outp;
  Mult mult;
  Inp inp;
  DepParam<int> p2;

  SC_CTOR(Top) : outp("outp"), mult("mult"), inp("inp"), p2("p2") {
    outp.clk(clk);
    outp.i(w4);
    mult.clk(clk);
    mult.k(w2);
    mult.i(w3);
    mult.o(w4);
    inp.clk(clk);
    inp.o(w3);
    p2.i(k);
    p2.o(w2);
  }
};
