// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.2)
// from file(s) main.hcl, on 2019-11-07 at 19:02:13, by jserot
// -------------------------------------------------------------------------------

#include <systemc.h>
#include <iostream>
#include "bcast.h"
#include "Read_YUV_act.h"
#include "Display_YUV_act.h"
#include "Diff_act.h"
#include "Delay_act.h"
#include "index_param.h"
#include "ival_param.h"
#include "height_param.h"
#include "width_param.h"

int sc_main(int argc, char* argv[]) {
  sc_fifo<int > w18("w18", 4);
  sc_fifo<int > w17("w17", 4);
  sc_fifo<int > w1("w1", 4);
  sc_fifo<int > w2("w2", 4);
  sc_fifo<int > w7("w7", 4);
  sc_fifo<int > w8("w8", 4);
  sc_fifo<uchar > w10("w10", 102000);
  sc_fifo<uchar > w9("w9", 102000);
  sc_fifo<int > w3("w3", 4);
  sc_fifo<int > w4("w4", 4);
  sc_fifo<int > w5("w5", 4);
  sc_fifo<uchar > w6("w6", 102000);
  sc_fifo<int > w11("w11", 4);
  sc_fifo<int > w12("w12", 4);
  sc_fifo<int > w13("w13", 4);
  sc_fifo<uchar > w16("w16", 102000);
  sc_fifo<uchar > w15("w15", 102000);
  sc_fifo<uchar > w14("w14", 102000);

  sc_clock clk("clk", 10, SC_NS, 0.5);

  bcast4<int > bcast_12("bcast_12");
  bcast_12.i(w18);
  bcast_12.o_1(w1);
  bcast_12.o_2(w7);
  bcast_12.o_3(w3);
  bcast_12.o_4(w12);
  bcast4<int > bcast_11("bcast_11");
  bcast_11.i(w17);
  bcast_11.o_1(w2);
  bcast_11.o_2(w8);
  bcast_11.o_3(w4);
  bcast_11.o_4(w13);
  Read_YUV_act Read_YUV("Read_YUV", false);
  Read_YUV.clk(clk);
  Read_YUV.width(w1);
  Read_YUV.height(w2);
  Read_YUV.y(w10);
  Read_YUV.u(w15);
  Read_YUV.v(w14);
  Diff_act Diff("Diff", false);
  Diff.clk(clk);
  Diff.width(w7);
  Diff.height(w8);
  Diff.input(w10);
  Diff.previous(w9);
  Diff.output(w6);
  Diff.result(w16);
  Delay_act Delay("Delay", false);
  Delay.clk(clk);
  Delay.width(w3);
  Delay.height(w4);
  Delay.ival(w5);
  Delay.input(w6);
  Delay.output(w9);
  Display_YUV_act Display_YUV("Display_YUV", false);
  Display_YUV.clk(clk);
  Display_YUV.id(w11);
  Display_YUV.width(w12);
  Display_YUV.height(w13);
  Display_YUV.y(w16);
  Display_YUV.u(w15);
  Display_YUV.v(w14);
  index_param index("index");
  index.clk(clk);
  index.o(w11);
  ival_param ival("ival");
  ival.clk(clk);
  ival.o(w5);
  height_param height("height");
  height.clk(clk);
  height.o(w17);
  width_param width("width");
  width.clk(clk);
  width.o(w18);

  sc_start();
  return EXIT_SUCCESS;
}
