-- Generated by pi2hcl from files mini.hcl and mini.names

type int;

#pragma code("inp", "include/input.h", "input", "inputInit");
#pragma code("foo", "include/foo.h", "foo");
#pragma code("outp", "include/output.h", "output", "outputInit");

actor inp in () out (o: int);
actor foo in (i: int) out (o: int);
actor outp in (i: int) out ();

let x = inp ()
let y = foo x
let () = outp y
