-- Generated by pi2hcl from file examples/sobel.hcl

type uchar;
type ;

#pragma code("Read_YUV", "./include/<tbd>", "readYUV", "initReadYUV");
#pragma code("Merge", "./include/<tbd>", "merge");
#pragma code("Sobel", "./include/<tbd>", "sobel");
#pragma code("Split", "./include/<tbd>", "split");
#pragma code("display", "./include/<tbd>", "yuvDisplay", "yuvDisplayInit");

actor Read_YUV param (width: int,height: int) in () out (y: unsigned char,u: unsigned char,v: unsigned char);
actor Merge param (nbSlice: int,width: int,height: int) in (input: unsigned char) out (output: unsigned char);
actor Sobel param (width: int,height: int) in (input: unsigned char) out (output: unsigned char);
actor Split param (nbSlice: int,width: int,height: int) in (input: unsigned char) out (output: unsigned char);
actor display param (id: int,width: int,height: int) in (y: unsigned char,u: unsigned char,v: unsigned char) out ();

