-- Generated by pi2hcl from files sobel.hcl and sobel.names

type uchar;
type nat;

parameter width: nat = 352;
parameter height: nat = 288;
parameter index: nat = 0;
parameter nbSlice: nat = 8;
parameter sliceHeight: nat = height/nbSlice+2;

#pragma code("Read_YUV", "Code/include/yuvRead.h", "readYUV", "initReadYUV");
#pragma code("Split", "Code/include/splitMerge.h", "split");
#pragma code("Sobel", "Code/include/sobel.h", "sobel");
#pragma code("Merge", "Code/include/splitMerge.h", "merge");
#pragma code("display", "Code/include/yuvDisplay.h", "yuvDisplay", "yuvDisplayInit");

actor Read_YUV
  param (width: int, height: int)
  in ()
  out (y: unsigned char "height*width", u: unsigned char "height/2*width/2", v: unsigned char "height/2*width/2");
actor Split
  param (nbSlice: int, width: int, height: int)
  in (input: unsigned char "height*width")
  out (output: unsigned char "nbSlice*width*(height/nbSlice+2)");
actor Sobel
  param (width: int, height: int)
  in (input: unsigned char "height*width")
  out (output: unsigned char "height*width");
actor Merge
  param (nbSlice: int, width: int, height: int)
  in (input: unsigned char "nbSlice*width*(height/nbSlice+2)")
  out (output: unsigned char "height*width");
actor display
  param (id: int, width: int, height: int)
  in (y: unsigned char "height*width", u: unsigned char "height/2*width/2", v: unsigned char "height/2*width/2")
  out ();

let (y1,u,v) = Read_YUV (width,height) ();
let y2 = Split (nbSlice,width,height) y1;
let y3 = Sobel (width,sliceHeight) y2;
let y4 = Merge (nbSlice,width,height) y3;
let () = display (index,width,height) (y4,u,v);
