SRCS=main.hcl
GEN_OPTS=-dump_typed #-dump_ir
DOT_OPTS=-target_dir ./dot -dot_show_indexes -dot_slotted_boxes
SYSTEMC_OPTS=-target_dir systemc -sc_stop_time 100 #-sc_trace
PREESM_OPTS=-target_dir preesm


include ../../../../lib/etc/Makefile.app
