SRCS=main.hcl
GEN_OPTS=#-dump_ir
DOT_OPTS=-target_dir ./dot -dot_show_indexes
PREESM_OPTS=-target_dir preesm
SYSTEMC_OPTS=-target_dir systemc -sc_stop_time 100
PREESM_OPTS=-target_dir ./preesm
PREESM_REP=/Users/jserot/Desktop/SF2/preesm-dev/param21
PREESM_PROJ=param1


include ../../../../lib/etc/Makefile.app
