SRCS=main.hcl
GEN_OPTS=
DOT_OPTS=-target_dir ./dot -dot_slotted_boxes #-insert_bcasts
SYSTEMC_OPTS=-target_dir ./systemc -sc_default_fifo_capacity 102000
#PREESM_OPTS=-preesm_top_name top_sobel -target_dir ./preesm
PREESM_OPTS=-target_dir ./preesm

include ../../../../lib/etc/Makefile.app
