// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.1)
// from file(s) /Users/jserot/Dev/ml/hocl/lib/hocl/prelude.hcl,main.hcl, on 2019-05-18 at 10:11:10, by jserot
// -------------------------------------------------------------------------------

#include "foo_act.h"
#include "../code/include/foo.h"

void foo_act::main(void) {
    while ( 1 ) { 
      wait(); // clk
      _i = i.read();
      _k = k.read();
      foo(_k, &_i, &_o);
      o.write(_o);
    }
}
