// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.1)
// from file(s) /Users/jserot/Dev/ml/hocl/lib/hocl/prelude.hcl,main.hcl, on 2019-05-18 at 10:11:10, by jserot
// -------------------------------------------------------------------------------

#include "inp_act.h"
#include "../code/include/input.h"

void inp_act::main(void) {
    inputInit();
    while ( 1 ) { 
      wait(); // clk
      input(&_o);
      o.write(_o);
    }
}
