// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.1)
// from file(s) /Users/jserot/Dev/ml/hocl/lib/hocl/prelude.hcl,main.hcl, on 2019-05-18 at 10:11:10, by jserot
// -------------------------------------------------------------------------------

#include <systemc.h>
#include <iostream>
#include "inp_act.h"
#include "foo_act.h"
#include "outp_act.h"
#include "multFactor_act.h"

int sc_main(int argc, char* argv[]) {
  sc_fifo<int > w3("w3", 256);
  sc_signal<int > w1("w1");
  sc_fifo<int > w2("w2", 256);

  sc_clock clk("clk", 10, SC_NS, 0.5);

  outp_act outp("outp", false);
  outp.clk(clk);
  outp.i(w3);
  foo_act foo("foo", false);
  foo.clk(clk);
  foo.k(w1);
  foo.i(w2);
  foo.o(w3);
  inp_act inp("inp", false);
  inp.clk(clk);
  inp.o(w2);
  multFactor_act multFactor("multFactor");
  multFactor.clk(clk);
  multFactor.o(w1);

  sc_start(100, SC_NS);
  cout << "Simulation stopped at t=" << sc_time_stamp() << "\n";
  return EXIT_SUCCESS;
}
