// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.1)
// from file(s) /Users/jserot/Dev/ml/hocl/lib/hocl/prelude.hcl,main.hcl, on 2019-05-18 at 10:11:10, by jserot
// -------------------------------------------------------------------------------

#ifndef _multFactor_act_h
#define _multFactor_act_h

#include <systemc.h>
#include "hocl.h"

SC_MODULE(multFactor_act) {
  sc_in<bool> clk;
  sc_out<int > o;

  void main(void);

  SC_HAS_PROCESS(multFactor_act);

  multFactor_act(sc_module_name name_ ) :
    modname(name_), sc_module(name_)  {
    SC_THREAD(main);
    sensitive << clk.pos();
  }

  ~multFactor_act() { }

  private:
    // Local variables
    int _o;
    // Service
    sc_module_name modname;
};
#endif
