// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.1)
// from file(s) /Users/jserot/Dev/ml/hocl/lib/hocl/prelude.hcl,main.hcl, on 2019-05-18 at 10:11:10, by jserot
// -------------------------------------------------------------------------------

#include "multFactor_act.h"

void multFactor_act::main(void) {
    while ( 1 ) { 
      wait(); // clk
      _o = 2;
      o.write(_o);
    }
}
