#!/bin/bash
# A script for automated testing 

TMP=/tmp/do_test.out
DOTVIEWER=graphviz

function try_make
{
case $1 in
*) make dot;;
esac
case $? in
0) echo "OK";;
*) echo "FAILED";;
esac
}

echo -n "Testing $1 in $2... "
(cd $2; try_make $1 && make clean) > $TMP 2>&1
grep "OK" $TMP >/dev/null && echo -e "\033[32mOK\033[0m"
grep "FAILED" $TMP >/dev/null && echo -e "\033[31mFAILED\033[0m"
grep "OK" $TMP >/dev/null && exit 1
exit 0
