SRCS=main.hcl
GEN_OPTS=-dump_typed
DOT_OPTS=-target_dir ./dot -dot_slotted_boxes
SYSTEMC_OPTS=-target_dir systemc
PREESM_OPTS=-target_dir preesm
XDF_OPTS=-target_dir xdf

include ../../../lib/etc/Makefile.app
