SRCS=main.hcl
GEN_OPTS=-prelude ../../../../lib/hocl/prelude.hcl
# SYSTEMC_OPTS=-target_dir systemc
# PREESM_OPTS=-target_dir preesm
# XDF_OPTS=-target_dir xdf

include ../../../../lib/etc/Makefile.app
