SRCS=main.hcl
GEN_OPTS=-insert_bcasts
DOT_OPTS=-target_dir ./dot -dot_slotted_boxes
SYSTEMC_OPTS=-target_dir systemc -sc_stop_time 100 # -insert_bcasts implicit here
PREESM_OPTS=-target_dir preesm # -insert_bcasts implicit here 

include ../../../../lib/etc/Makefile.app
