// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.2)
// from file(s) main.hcl, on 2019-10-30 at 19:28:53, by jserot
// -------------------------------------------------------------------------------

#include "index_param.h"

void index_param::main(void) {
    while ( 1 ) { 
      wait(clk.posedge_event());
      _o = 0;
      o.write(_o);
    }
}
