// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.2)
// from file(s) main.hcl, on 2019-10-30 at 19:28:53, by jserot
// -------------------------------------------------------------------------------

#include "Read_YUV_act.h"
#include "include/yuvRead.h"

void Read_YUV_act::main(void) {
    wait(clk.posedge_event());
    _width = width.read();
    _height = height.read();
    initReadYUV(_width, _height);
    while ( 1 ) { 
      _width = width.read();
      _height = height.read();
      _y = new uchar[_height*_width];
      _u = new uchar[_height/2*_width/2];
      _v = new uchar[_height/2*_width/2];
      readYUV(_width, _height, _y, _u, _v);
      for ( int __k=0; __k<_height*_width; __k++ ) y.write(_y[__k]);
      for ( int __k=0; __k<_height/2*_width/2; __k++ ) u.write(_u[__k]);
      for ( int __k=0; __k<_height/2*_width/2; __k++ ) v.write(_v[__k]);
      delete [] _y;
      delete [] _u;
      delete [] _v;
    }
}
