PROJ=hier3
SRCS=sub.hcl top.hcl
GEN_OPTS=#-dump_static #-dump_typed
DOT_OPTS=#-insert_bcasts
PREESM_OPTS=-target_dir preesm
SYSTEMC_OPTS=-target_dir systemc -sc_stop_time 100

include ../../../../lib/etc/Makefile.app
