SRCS=main.hcl
GEN_OPTS=
DOT_OPTS=-target_dir ./dot
PREESM_OPTS=-target_dir preesm
SYSTEMC_OPTS=-target_dir systemc -sc_stop_time 100
PREESM_OPTS=-target_dir ./preesm
PREESM_REP=/Users/jserot/Desktop/SF2/preesm-dev/param2
PREESM_PROJ=param2


include ../../../../lib/etc/Makefile.app
