-- Generated by pi2hcl from file Hblur2x.pi

type nat;
type int;
type float;

parameter tot_image_size: nat;
parameter nGpyrLayers: nat;
parameter parallelismLevel: nat;
parameter gWmax: nat;
parameter image_height: nat;
parameter image_width: nat;
parameter imgDouble: nat;

#pragma code("row_filter_transpose2x_1", "Code/include/ezsift-preesm.h", "row_filter_transpose2x_1", "");
#pragma code("BarrierTranspose2x_1", "Code/include/ezsift-preesm.h", "BarrierTranspose2x_1", "");
#pragma code("row_filter_transpose2x_2", "Code/include/ezsift-preesm.h", "row_filter_transpose2x_2", "");
#pragma code("BarrierTranspose2x_2", "Code/include/ezsift-preesm.h", "BarrierTranspose2x_2", "");

source iter_nb2 : int;
source gauss_coefs2 : float;
source col_sizes2 : int;
source iter_nb1 : int;
source iterPrev : float;
source col_sizes1 : int;
source imgOri : float;
source gauss_coefs1 : float;
actor row_filter_transpose2x_1
  param (image_height: int, image_width: int, imgDouble: int, nGpyrLayers: int, parallelismLevel: int, gWmax: int, tot_image_size: nat)
  in (gaussian_coefs: float "nGpyrLayers*gWmax", img: float "if(imgDouble,(4*tot_image_size)/parallelismLevel,1)", column_sizes: int "nGpyrLayers", imgIterPrev: float "if(imgDouble,(4*tot_image_size)/parallelismLevel,1)", iter: int "1")
  out (imgGT: float "if(imgDouble, (4*tot_image_size)/parallelismLevel, 1)");
actor BarrierTranspose2x_1
  param (image_width: int, image_height: int, imgDouble: int, parallelismLevel: int, tot_image_size: int)
  in (img_in: float "if(imgDouble, 4*tot_image_size, parallelismLevel)")
  out (img_out: float "if(imgDouble, 4*tot_image_size, parallelismLevel)");
actor row_filter_transpose2x_2
  param (image_height: int, image_width: int, imgDouble: int, nGpyrLayers: int, parallelismLevel: int, gWmax: int, tot_image_size: nat)
  in (column_sizes: int "nGpyrLayers", img: float "if(imgDouble, (4*tot_image_size)/parallelismLevel, 1)", gaussian_coefs: float "nGpyrLayers*gWmax", iter: int "1")
  out (imgGT: float "if(imgDouble, (4*tot_image_size)/parallelismLevel, 1)");
actor BarrierTranspose2x_2
  param (image_width: int, image_height: int, imgDouble: int, parallelismLevel: int, tot_image_size: int)
  in (img_in: float "if(imgDouble, 4*tot_image_size, parallelismLevel)")
  out (img_out: float "if(imgDouble, 4*tot_image_size, parallelismLevel)");
sink imgBlurred : float;

let iter_nb2_iter_nb2 = iter_nb2 ();
let gauss_coefs2_gauss_coefs2 = gauss_coefs2 ();
let col_sizes2_col_sizes2 = col_sizes2 ();
let iter_nb1_iter_nb1 = iter_nb1 ();
let iterPrev_iterPrev = iterPrev ();
let col_sizes1_col_sizes1 = col_sizes1 ();
let imgOri_imgOri = imgOri ();
let gauss_coefs1_gauss_coefs1 = gauss_coefs1 ();
let row_filter_transpose2x_1_imgGT = row_filter_transpose2x_1 (image_height,image_width,imgDouble,nGpyrLayers,parallelismLevel,gWmax,tot_image_size) (gauss_coefs1_gauss_coefs1,imgOri_imgOri,col_sizes1_col_sizes1,iterPrev_iterPrev,iter_nb1_iter_nb1);
let BarrierTranspose2x_1_img_out = BarrierTranspose2x_1 (image_width,image_height,imgDouble,parallelismLevel,tot_image_size) row_filter_transpose2x_1_imgGT;
let row_filter_transpose2x_2_imgGT = row_filter_transpose2x_2 (image_height,image_width,imgDouble,nGpyrLayers,parallelismLevel,gWmax,tot_image_size) (col_sizes2_col_sizes2,BarrierTranspose2x_1_img_out,gauss_coefs2_gauss_coefs2,iter_nb2_iter_nb2);
let BarrierTranspose2x_2_img_out = BarrierTranspose2x_2 (image_width,image_height,imgDouble,parallelismLevel,tot_image_size) row_filter_transpose2x_2_imgGT;
let () = imgBlurred BarrierTranspose2x_2_img_out;
