SRCS=main.hcl
GEN_OPTS=
DOT_OPTS=-target_dir ./dot -dot_slotted_boxes
DOT_OPTS=-target_dir ./dot -dot_slotted_boxes
SYSTEMC_OPTS=-target_dir ./systemc -sc_stop_time 100 -sc_trace
PREESM_REP=/Users/jserot/Desktop/SF2/preesm-dev
PREESM_OPTS=-target_dir preesm

include ../../../../lib/etc/Makefile.app
