// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.2)
// from file(s) main.hcl, on 2019-11-07 at 19:02:13, by jserot
// -------------------------------------------------------------------------------

#include "Diff_act.h"
#include "include/difference.h"

void Diff_act::main(void) {
    while ( 1 ) { 
      _width = width.read();
      _height = height.read();
      _input = new uchar[_height*_width];
      _previous = new uchar[_height*_width];
      _output = new uchar[_height*_width];
      _result = new uchar[_height*_width];
      for ( int __k=0; __k<_height*_width; __k++ ) _input[__k] = input.read();
      for ( int __k=0; __k<_height*_width; __k++ ) _previous[__k] = previous.read();
      difference(_width, _height, _input, _previous, _output, _result);
      for ( int __k=0; __k<_height*_width; __k++ ) output.write(_output[__k]);
      for ( int __k=0; __k<_height*_width; __k++ ) result.write(_result[__k]);
      delete [] _input;
      delete [] _previous;
      delete [] _output;
      delete [] _result;
    }
}
