SRCS=main.hcl
GEN_OPTS=-insert_bcasts
DOT_OPTS=-dot_slotted_boxes
PREESM_OPTS=-target_dir preesm # -insert_bcasts implicit here 
SYSTEMC_OPTS=-target_dir systemc -sc_stop_time 100 # -insert_bcasts implicit here

include ../../../../lib/etc/Makefile.app
