SRCS=main.hcl
GEN_OPTS=-dump_ir 
DOT_OPTS=-target_dir ./dot -dot_slotted_boxes -dot_show_indexes
SYSTEMC_OPTS=-target_dir ./systemc -sc_stop_time 50 -sc_trace
PREESM_OPTS=-target_dir preesm
PREESM_REP=/Users/jserot/Desktop/SF2/preesm-dev/sdf3
PREESM_PROJ=sdf3

include ../../../../lib/etc/Makefile.app
