// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.2)
// from file(s) main.hcl, on 2019-10-30 at 17:58:47, by jserot
// -------------------------------------------------------------------------------

#include <systemc.h>
#include <iostream>
#include "bcast.h"
#include "Read_YUV_act.h"
#include "Display_YUV_act.h"
#include "index_param.h"
#include "height_param.h"
#include "width_param.h"

int sc_main(int argc, char* argv[]) {
  sc_fifo<int > w10("w10", 4);
  sc_fifo<int > w9("w9", 4);
  sc_fifo<int > w1("w1", 4);
  sc_fifo<int > w2("w2", 4);
  sc_fifo<int > w3("w3", 4);
  sc_fifo<int > w4("w4", 4);
  sc_fifo<int > w5("w5", 4);
  sc_fifo<uchar > w8("w8", 102000);
  sc_fifo<uchar > w7("w7", 102000);
  sc_fifo<uchar > w6("w6", 102000);

  sc_clock clk("clk", 10, SC_NS, 0.5);

  bcast2<int > bcast_7("bcast_7");
  bcast_7.i(w10);
  bcast_7.o_1(w1);
  bcast_7.o_2(w4);
  bcast2<int > bcast_6("bcast_6");
  bcast_6.i(w9);
  bcast_6.o_1(w2);
  bcast_6.o_2(w5);
  Read_YUV_act Read_YUV("Read_YUV", false);
  Read_YUV.clk(clk);
  Read_YUV.width(w1);
  Read_YUV.height(w2);
  Read_YUV.y(w8);
  Read_YUV.u(w7);
  Read_YUV.v(w6);
  Display_YUV_act Display_YUV("Display_YUV", false);
  Display_YUV.clk(clk);
  Display_YUV.id(w3);
  Display_YUV.width(w4);
  Display_YUV.height(w5);
  Display_YUV.y(w8);
  Display_YUV.u(w7);
  Display_YUV.v(w6);
  index_param index("index");
  index.clk(clk);
  index.o(w3);
  height_param height("height");
  height.clk(clk);
  height.o(w9);
  width_param width("width");
  width.clk(clk);
  width.o(w10);

  sc_start();
  return EXIT_SUCCESS;
}
