PROJ=param1
SRCS=main.hcl
MAIN=main
DOT_OPTS=#-insert_bcasts # Uncomment to show the inserted bcast node
PREESM_OPTS=-target_dir preesm
SYSTEMC_OPTS=-target_dir systemc -sc_stop_time 100 -dump_static


include ../../../../lib/etc/Makefile.app
