// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.2)
// from file(s) main.hcl, on 2019-11-05 at 15:07:51, by jserot
// -------------------------------------------------------------------------------

#ifndef _height_param_h
#define _height_param_h

#include <systemc.h>
#include "hocl.h"

SC_MODULE(height_param) {
  sc_in<bool> clk;
  sc_fifo_out<int > o;

  void main(void);

  SC_HAS_PROCESS(height_param);

  height_param(sc_module_name name_ ) :
    modname(name_), sc_module(name_)  {
    SC_THREAD(main);
  }

  ~height_param() { }

  private:
    // Local variables
    int _o;
    // Service
    sc_module_name modname;
};
#endif
