// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.2)
// from file(s) main.hcl, on 2019-11-05 at 15:07:51, by jserot
// -------------------------------------------------------------------------------

#ifndef _Sobel_act_h
#define _Sobel_act_h

#include <systemc.h>
#include "hocl.h"

SC_MODULE(Sobel_act) {
  sc_in<bool> clk;
  sc_fifo_in<int > width;
  sc_fifo_in<int > height;
  sc_fifo_in<uchar > input;
  sc_fifo_out<uchar > output;

  void main(void);

  SC_HAS_PROCESS(Sobel_act);

  Sobel_act(sc_module_name name_, bool trace_=false  ) :
    modname(name_), sc_module(name_), trace(trace_) 
  {
    SC_THREAD(main);
  }

  ~Sobel_act() { }

  private:
    // Local variables
    int _width;
    int _height;
    uchar *_input;
    uchar *_output;
    // Service
    bool trace;
    sc_module_name modname;
};
#endif
