// -------------------------------------------------------------------------------
// This file has been automatically generated by the HoCL compiler (version 0.2)
// from file(s) main.hcl, on 2019-11-05 at 15:07:51, by jserot
// -------------------------------------------------------------------------------

#include "Sobel_act.h"
#include "include/sobel.h"

void Sobel_act::main(void) {
    while ( 1 ) { 
      _width = width.read();
      _height = height.read();
      _input = new uchar[_height*_width];
      _output = new uchar[_height*_width];
      for ( int __k=0; __k<_height*_width; __k++ ) _input[__k] = input.read();
      sobel(_width, _height, _input, _output);
      for ( int __k=0; __k<_height*_width; __k++ ) output.write(_output[__k]);
      delete [] _input;
      delete [] _output;
    }
}
